kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {site}-{node}-{experiment}-{rsync_module}
  namespace: scraper
  labels:
    app: {site}-{node}-{experiment}-{rsync_module}
    version: test
spec:
  replicas: 1
  template:
    metadata:
      name: {site}-{node}-{experiment}-{rsync_module}
      labels:
        app: {site}-{node}-{experiment}-{rsync_module}
        version: test
    spec:
      containers:
        - name: {site}-{node}-{experiment}-{rsync_module}
          image: gcr.io/mlab-staging/github-pboothe-scraper:test
          env:
            - name: RSYNC_MODULE
              value: {rsync_module}
            - name: RSYNC_HOST
              value: {rsync_host}
            - name: SPREADSHEET
              value: 143pU25GJidW2KZ_93hgzHdqTqq22wgdxR_3tt3dvrJY
            - name: GCS_BUCKET
              value: mlab-scraper-staging
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
